#staging
deployment:
  user: the-ssh-user
  from: ./
  to: /var/www/vhosts/example.com/www
  excludes:
    - fileadmin/*
    - typo3temp/*
    - uploads/*
    - .htaccess
    - .htpasswd
  strategy: rsync
releases:
  enabled: true
  max: 5
  symlink: current
  directory: releases
hosts:
  - server-host
tasks:
  pre-deploy:
  on-deploy:
  post-release:
  post-deploy: